name: Deploy to ACA (dev)

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  RESOURCE_GROUP: test-dev-scus-rg
  CONTAINER_APP_NAME: test1-dev-scus-aca
  CONTAINER_APP_ENV_NAME: test-dev-scus-cae
  
  ACR_NAME: testDevScusAcr
  ACR_LOGIN: testdevscusacr
  IMAGE_NAME: hello-world-app
  IMAGE_LATEST: testdevscusacr.azurecr.io/hello-world-app:latest

jobs:
  build-and-deploy:
    environment: dev

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to Azure Container Registry & Build and Push Docker Image
        run: |
          az acr login --name ${{ env.ACR_NAME }}
          IMAGE_NAME=${{ env.ACR_LOGIN }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
          docker build -t $IMAGE_NAME -f Dockerfile.linux .
          docker push $IMAGE_NAME

      - name: Deploy to Azure Container Apps Test1
        uses: azure/container-apps-deploy-action@v1
        with:
          containerAppName: ${{ env.CONTAINER_APP_NAME }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          imageToDeploy: ${{ env.ACR_LOGIN }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
          containerAppEnvironment: ${{ env.CONTAINER_APP_ENV_NAME }}